words:
  - astrojs
  - Bitnami
  - bitpushr
  - cloudnative
  - clusterissuer
  - CNPG
  - Collabora
  - Dockerhub
  - downscaling
  - Dragonfish
  - frontmatter
  - heavyscript
  - hyperconverged
  - Jagr
  - jagrbombs
  - Jailman
  - Jellyfin
  - Kjeld
  - kofeh
  - kqmaverick
  - kubeapps
  - Merch
  - metallb
  - Minio
  - Nextcloud
  - Noob
  - notoriosly
  - ornias
  - pagefind
  - Photoprism
  - Pihole
  - Postgreqsql
  - preconfigured
  - Prowlarr
  - Radarr
  - Schouten
  - sdimovv
  - shadofall
  - shoutout
  - showstealers
  - Sidero
  - statefulset
  - statefulsets
  - Syncthing
  - tailscale
  - TCCR
  - templating
  - Traefik
  - truecharts
  - upscaling
  - Vaultwarden
  - Xstar
  - Xsystems
