name: Deploy to GitHub Pages

concurrency:
  group: deploy-docs
on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      #- name: Set Swap Space
      #  uses: pierotofy/set-swap-space@master
      #  with:
      #    swap-size-gb: 10
          
      - uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
        with:
          path: build
          fetch-depth: 1
          token: ${{ secrets.BOT_TOKEN }}
          ref: gh-pages
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules/.cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
          
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --frozen-lockfile
        env:
          NODE_OPTIONS: "--max-old-space-size=10000"
          DOCUSAURUS_SSR_CONCURRENCY: 3
          SKIP_HTML_MINIFICATION: false
          
        
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
        env: 
          NODE_OPTIONS: "--max-old-space-size=10000"
          DOCUSAURUS_SSR_CONCURRENCY: 3
          SKIP_HTML_MINIFICATION: false

      - name: Create commit
        uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80 # tag=v4
        with:
          commit_message: "chore: update docs"
          commit_user_name: truecharts-bot
          commit_user_email: bot@truecharts.org
          commit_author: truecharts-bot <bot@truecharts.org>
          repository: ./build
