name: Build and Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
          
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 18
          cache: yarn
          
      - name: Cache docusaurus cache
        id: cache-ds
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        env:
          cache-name: cache-ds-cache
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-ds.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
          
      - uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b # v4.2.0
        with:
          cmd: install --frozen-lockfile
        env:
          NODE_OPTIONS: "--max-old-space-size=15000"
          DOCUSAURUS_SSR_CONCURRENCY: 3
          SKIP_HTML_MINIFICATION: false
        
      - uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b # v4.2.0
        with:
          cmd: build
        env: 
          NODE_OPTIONS: "--max-old-space-size=15000"
          DOCUSAURUS_SSR_CONCURRENCY: 3
          SKIP_HTML_MINIFICATION: false

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1
        if: github.event_name != 'pull_request'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: website
          directory: ./build
